name: CI

on: [pull_request]

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox
        python -m pip install pyspelling
        # Install any additional libraries required: additional plugins, documentation building libraries, etc.
    - name: Install Aspell
      run: |
        sudo apt-get install aspell aspell-en aspell-fr aspell-it
    - name: Spell check
      run: |
        egrep -lRZ '’' . | xargs -0 -l sed -i -e "s/’/\'/g"
        python -m pyspelling -c pyspellingconf.yaml
